language: ruby
rvm:
- 2.1
before_script:
- chmod +x ./script/cibuild
- pwd
script: ./script/cibuild
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
deploy:
  provider: s3
  access_key_id:
    secure: DXbPIZoniqrC/0/EciCE3S3wrFOjXoClmCZGlhvOzTO2Kzm4dT0+tNzsqnMQoTXwetMyAlXVsXRPZOY1c34vfqe1UONCl9Njb6+0pj0S8MZMAJwFvGXoLKPAMJQoqohijjqUTSBfZdqcnrRuyX3Eail2U/BsBk/v5VO942HQ+RcNFl2N/korvSf/YW3iN7jb82IRSfiYzMgcCADCii1ARZzBaJ55wTt0qS6zseZO6VfRz8whJUpHqYFfWtO9O82fC488HtKYllooG58vlCN5FC+mA08FnZvD5AugpVj0BMjNMqKSPto+G/lsChja1mAXf4OM16zdOXx2/M63Cqz4YYq28qMqhhys2N/i/gO6EthjcZq7GMMv9vZJLZJkV3PPhnxVBE5JHQsOn3Xpi6iM8H1epMlH2fx2ZbjIb/fk51tSGlmVfCEogXV4LQSfhZAQ3Gaqlaru6WrYz/SxRJuL7980tZtV+xISrJGUP4SCkN4MfZElnuY8ybh7/yeKEsUwV5nCVaVoJTfQNYfOtODWRkzm3xQn+si3Cly03IIbAPP4+cgKZT40hBFM1Pi4Xmkvo4aQFHc9XF8dumzVgZpgTKUlZvZDn1K4hAn4MYBLUTXrTOfwLWrQmtVwjvNd46Kohk2jtdJw6l+jDKzgPfURlqoDt8FotRHau26J3qkfCas=
  secret_access_key:
    secure: TePlDwGQJ1zmAb1CbPcLiDIbkcqgb+Sdx53d0XnPCYO7jR5AVLHzXTcOAphUnoRA3OxlYUmFpUiVkksnzOTD8963Kmy2q8lXnMMvf4xPdbMFHeCxi+nBZajIRkW9gFBU8B+uQx/GEQwVTewhPFj2Fm3fIifw+ksfvHPpYJlv23JmpC159Az0+5rNmCRzLbh5TTfJR4AhbKHE3XPxI0aolG6RsVVwn70ettDp6koT769n4nzWPzENw7CTFbVGwLXZJ5kFrP71Baz24bkKJGd5+7O11aqLU8/ZV4FVLZspqZuT0vXXPsHDrVTSLzxAm7C0RnW+cK9sYJ3ynXb3QAtjcr4dLMscrjWRZvvV308jF7sC6JQ42LVuGSpM39vvglOfEMDExDKCbFo7to6ljRRuRpAOjntTRpl4HtC0i515uO1dCDry0YaZOJwRgXeqZcSM89pqHeqJGHT3RRfJ9u7AYtX5B8+oUsPkAhEhLoX++ufGfHrNsu5Qc0eSerlke4xKndx1wY3M24yzxn6ot12nbSRTeaJOkocwM4pU2qJTDucnEOHSvk/yewKVXuGrjITvCIGPFEGcI6+yBOA7my5O5OZEHEGOLA896MOZriwqhF62q2LLes9btjAftUcd0wP3d2mQauG8rAjNtsa5JjNAapLUTQey5NE4bLVHQceW/U0=
  bucket: "highlandr.com"
